import { prisma } from '../src/lib/prisma.js';

export const proposedHerbs = [
  {
    localName: 'Abukado',
    scientificName: 'Persea americana',
    cebuanoName: 'Abokado',
    englishName: 'Avocado',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Decoction of leaves used for diarrhea, abdominal discomfort, and mild hypertension; seed paste traditionally applied for skin eruptions.',
    preparationMethod: 'Boil 5-7 clean mature leaves in 2 cups of water for 10-15 minutes. Cool and strain.',
    dosage: 'Drink 1/2 cup twice daily after meals.',
    warnings: 'Avoid excessive intake during pregnancy. Leaves contain persin; consult healthcare provider if taking blood thinners.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Persea americana) & Philippine National Formulary.',
  },
  {
    localName: 'Adgaw',
    scientificName: 'Premna odorata',
    cebuanoName: 'Alagaw',
    englishName: 'Fragrant Premna',
    category: 'Respiratory',
    medicinalUses: 'Infusion or decoction of leaves used for cough, bronchitis, fever, gas pain in infants, and as a mouthwash for toothache.',
    preparationMethod: 'Boil 8-10 fresh leaves in 3 cups of water for 15 minutes. Strain before drinking.',
    dosage: 'Drink 1/2 to 1 cup 3 times a day for cough and fever.',
    warnings: 'Safe for general adult use; prepare fresh daily.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Premna odorata).',
  },
  {
    localName: 'Agas-ahas',
    scientificName: 'Euphorbia tirucalli',
    cebuanoName: 'Bali-bali',
    englishName: 'Pencil Cactus / Milk Bush',
    category: 'Dermatological (Caution)',
    medicinalUses: 'Diluted latex traditionally applied topically with extreme care for stubborn warts, calluses, and ringworm.',
    preparationMethod: 'External only: Apply a minute drop of fresh milky sap directly onto the wart with a cotton bud, avoiding surrounding healthy skin.',
    dosage: 'Once daily topically until lesion dries up. Wash thoroughly after 15 minutes.',
    warnings: 'HIGHLY IRRITANT AND TOXIC: Never ingest. Keep strictly away from eyes to avoid corneal ulceration and temporary blindness.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Euphorbia tirucalli).',
  },
  {
    localName: 'Agosip',
    scientificName: 'Symplocos cochinchinensis',
    cebuanoName: 'Kagagahan',
    englishName: 'Sapphire Berry',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Bark and leaf decoctions used as an astringent gargle for bleeding gums, oral aphthae, and washing chronic ulcers.',
    preparationMethod: 'Boil 10g dried shredded bark in 2 cups of water for 15 minutes. Use cooled liquid as mouthwash.',
    dosage: 'Gargle 1/4 cup 2-3 times daily. Do not swallow large amounts.',
    warnings: 'Astringent: may cause mild constipation if swallowed repeatedly.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Symplocos cochinchinensis).',
  },
  {
    localName: 'Alang-ilang de China',
    scientificName: 'Desmos chinensis',
    cebuanoName: 'Alang-ilang sa bukid',
    englishName: 'Dwarf Ylang-ylang',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Roots and aromatic flowers used as a calming herbal wash and postpartum bath to alleviate muscular soreness.',
    preparationMethod: 'Simmer roots and floral bracts in warm bath water for postpartum recovery wash.',
    dosage: 'Warm topical wash once daily for postpartum recuperation.',
    warnings: 'External use preferred. Do not apply directly over fresh surgical wounds.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Desmos chinensis).',
  },
  {
    localName: 'Alipata',
    scientificName: 'Excoecaria agallocha',
    cebuanoName: 'Buta-buta',
    englishName: 'Blind-your-eye Mangrove',
    category: 'Dermatological (Caution)',
    medicinalUses: 'Historical coastal folk application for persistent ulcers and parasitic skin infections.',
    preparationMethod: 'Decoction of bark used strictly externally as an astringent wash.',
    dosage: 'External wash only: rinse affected skin surface once daily.',
    warnings: 'DANGEROUS: Sap causes severe chemical conjunctivitis and temporary blindness. Ingestion is toxic.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Excoecaria agallocha).',
  },
  {
    localName: 'Alpasotes',
    scientificName: 'Dysphania ambrosioides',
    cebuanoName: 'Apasote',
    englishName: 'Mexican Tea / Wormseed',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Traditional carminative for flatulence, stomach cramps, and historical anthelmintic for intestinal roundworms.',
    preparationMethod: 'Infuse 1-2 small fresh leaves in 1 cup of boiling water for 10 minutes. Strain carefully.',
    dosage: 'Drink 1/2 cup once daily for digestive spasms for no more than 3 consecutive days.',
    warnings: 'TOXIC IN HIGH DOSES: Essential oil (ascaridole) is toxic. Strictly contraindicated in pregnancy and lactation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Dysphania ambrosioides).',
  },
  {
    localName: 'Anibong',
    scientificName: 'Oncosperma tigillarium',
    cebuanoName: 'Anibung',
    englishName: 'Nibung Palm',
    category: 'Renal & Diuretic',
    medicinalUses: 'Young shoot decoctions traditionally used as a mild cooling diuretic and tonic.',
    preparationMethod: 'Boil fresh palm hearts or tender shoots in 3 cups of water for 20 minutes.',
    dosage: 'Drink 1/2 cup twice daily for mild urinary discomfort.',
    warnings: 'Mild diuretic effect. Ensure adequate hydration.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Oncosperma tigillarium).',
  },
  {
    localName: 'Anito',
    scientificName: 'Emilia sonchifolia',
    cebuanoName: 'Tagulinaw',
    englishName: 'Lilac Tasselflower',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Fresh crushed leaves applied topically to soothe fevers, boils, and eye inflammation; leaf tea taken for cough.',
    preparationMethod: 'Crush fresh whole plant into a clean poultice, or boil 15g in 2 cups of water for 10 minutes.',
    dosage: 'Apply poultice for 20 minutes; drink 1/2 cup decoction twice daily for sore throat.',
    warnings: 'Contains trace pyrrolizidine alkaloids; do not consume continuously for prolonged periods.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Emilia sonchifolia).',
  },
  {
    localName: 'Apan-apan',
    scientificName: 'Sida acuta',
    cebuanoName: 'Wawalisan',
    englishName: 'Common Wireweed',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Roots and leaves boiled for fevers, headaches, dysentery, and poulticed on insect stings and boils.',
    preparationMethod: 'Boil 10g cleaned roots and leaves in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup 3 times daily during febrile episodes.',
    warnings: 'Avoid in pregnancy; monitor blood pressure if taking hypertensive medication.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Sida acuta).',
  },
  {
    localName: 'Apis',
    scientificName: 'Elephantopus tomentosus',
    cebuanoName: 'Dilang-toro',
    englishName: 'Woolly Elephant-foot',
    category: 'Renal & Diuretic',
    medicinalUses: 'Decoction of root and leaves taken to stimulate urination, relieve edema, and reduce fever.',
    preparationMethod: 'Boil 10g dried herb in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Do not use in severe kidney impairment without medical supervision.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Elephantopus tomentosus).',
  },
  {
    localName: 'Apitong',
    scientificName: 'Dipterocarpus grandiflorus',
    cebuanoName: 'Hagakhak-kahoy',
    englishName: 'Apitong Wood / Keruing',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Balsamic oleoresin historically applied topically as an antiseptic dressing for chronic indolent sores and ringworm.',
    preparationMethod: 'Apply a thin layer of refined resin or bark tincture to cleansed abrasions.',
    dosage: 'External dressing once daily covered with sterile gauze.',
    warnings: 'For external use only. Discontinue if contact dermatitis occurs.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Dipterocarpus grandiflorus).',
  },
  {
    localName: 'Asistasya',
    scientificName: 'Asystasia gangetica',
    cebuanoName: 'Ganges Primrose',
    englishName: 'Chinese Violet',
    category: 'Respiratory',
    medicinalUses: 'Leaf juice and decoction used for asthma, bronchial spasms, rheumatism, and soothing dry coughs.',
    preparationMethod: 'Boil a handful of leaves in 2 cups of water for 10 minutes, or extract fresh juice.',
    dosage: 'Drink 1/2 cup twice daily for bronchial spasms.',
    warnings: 'Safe culinary green in small amounts; avoid excessive quantities during early pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Asystasia gangetica).',
  },
  {
    localName: 'Bagtikan',
    scientificName: 'Parashorea malaanonan',
    cebuanoName: 'White Lauan cousin',
    englishName: 'Philippine Bagtikan',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Astringent bark decoction traditionally used by indigenous communities for acute dysentery and diarrhea.',
    preparationMethod: 'Boil 15g dried shredded bark in 3 cups of water down to 2 cups.',
    dosage: 'Drink 1/3 cup every 4-6 hours for acute diarrhea.',
    warnings: 'Do not use for more than 48 hours without medical consultation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Parashorea malaanonan).',
  },
  {
    localName: 'Bakawan',
    scientificName: 'Rhizophora mucronata',
    cebuanoName: 'Bakhaw',
    englishName: 'Red Mangrove / Loop-root Mangrove',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Rich in condensed tannins: bark decoction used as an antiseptic gargle, astringent wound wash, and for diarrhea.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes. Use for wash or gargle.',
    dosage: 'Gargle 1/4 cup 3 times daily; rinse skin sores twice daily.',
    warnings: 'Astringent: internal intake should be strictly limited to prevent gastric irritation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Rhizophora mucronata).',
  },
  {
    localName: 'Balanoy-parang',
    scientificName: 'Ocimum americanum',
    cebuanoName: 'Kambing-kambing',
    englishName: 'American Basil / Hoary Basil',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Aromatic leaf tea relieves flatulence, dyspepsia, stomach cramps, and provides mild fever relief.',
    preparationMethod: 'Steep 1 tablespoon fresh leaves in 1 cup boiling water for 10 minutes.',
    dosage: 'Drink 1 cup warm after meals.',
    warnings: 'Generally safe as culinary herb. Avoid therapeutic megadoses during pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ocimum americanum).',
  },
  {
    localName: 'Balete',
    scientificName: 'Ficus benjamina',
    cebuanoName: 'Dalakit',
    englishName: 'Weeping Fig',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Crushed leaves and bark poultice applied to relieve rheumatic joint pain, sprains, and contusions.',
    preparationMethod: 'Pound fresh leaves with coconut oil into a warm poultice and bind over affected joints.',
    dosage: 'Apply once daily for 30 minutes.',
    warnings: 'External only. Sap may trigger latex allergic reactions.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ficus benjamina).',
  },
  {
    localName: 'Balitbitan',
    scientificName: 'Cynometra ramiflora',
    cebuanoName: 'Oring',
    englishName: 'Wrinkled Pod Mangrove',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Seed oil and leaf paste traditionally applied to treat scabies, cutaneous herpes, and chronic eczema.',
    preparationMethod: 'Mix crushed seeds with neutral oil and apply topically to skin lesions.',
    dosage: 'Apply topically once daily at night. Wash off in the morning.',
    warnings: 'For topical use only. Do not ingest seed preparations.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Cynometra ramiflora).',
  },
  {
    localName: 'Bamban',
    scientificName: 'Donax canniformis',
    cebuanoName: 'Bamban-tubig',
    englishName: 'Donax Cane',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Fresh stem sap squeezed into eyes for mild conjunctival irritation; leaf decoction used for cooling fever baths.',
    preparationMethod: 'Boil clean leaves in bath water for cooling febrifuge soak.',
    dosage: 'Use warm bath water once daily during febrile restlessness.',
    warnings: 'Ensure strict sterility if using stem sap near ophthalmic tissues.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Donax canniformis).',
  },
  {
    localName: 'Bangkal',
    scientificName: 'Nauclea orientalis',
    cebuanoName: 'Mambog',
    englishName: 'Leichhardt Tree / Yellow Cheesewood',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Bitter bark decoction used as an antimalarial and febrifuge tonic, and as an antiseptic wash for infected wounds.',
    preparationMethod: 'Boil 10g dried shredded bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily for fever; use externally as wound wash.',
    warnings: 'Bitter tonic: high doses may cause nausea. Avoid during pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Nauclea orientalis).',
  },
  {
    localName: 'Bara-baras',
    scientificName: 'Gomphrena celosioides',
    cebuanoName: 'Botones-botones',
    englishName: 'Prostrate Globe Amaranth',
    category: 'Respiratory',
    medicinalUses: 'Decoction of flowers and leaves used for bronchial catarrh, stubborn cough, and mild urinary infections.',
    preparationMethod: 'Boil 10g floral heads in 2 cups of water for 10 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Safe in standard traditional amounts. Avoid in acute renal failure.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Gomphrena celosioides).',
  },
  {
    localName: 'Barit',
    scientificName: 'Pinus kesiya',
    cebuanoName: 'Pino',
    englishName: 'Benguet Pine / Khasi Pine',
    category: 'Respiratory',
    medicinalUses: 'Pine needles and oleoresin steam inhalation used for chest congestion, bronchitis, and topical antiseptic balms.',
    preparationMethod: 'Add a handful of fresh pine needles to a basin of boiling water and inhale the steam under a towel.',
    dosage: 'Steam inhalation for 10 minutes twice daily.',
    warnings: 'Do not ingest pure pine oil. Avoid direct skin contact with undiluted resin in patients with eczema.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pinus kesiya).',
  },
  {
    localName: 'Batino',
    scientificName: 'Alstonia macrophylla',
    cebuanoName: 'Batino-pula',
    englishName: 'Hard Alstonia',
    category: 'Cardiovascular',
    medicinalUses: 'Alkaloid-rich bark decoction used traditionally to lower blood pressure, soothe fevers, and stimulate appetite.',
    preparationMethod: 'Boil 5g dried bark in 2 cups of water for 15 minutes. Strain carefully.',
    dosage: 'Drink 1/4 cup twice daily before meals.',
    warnings: 'Potent alkaloid content: strictly adhere to dosage. Contraindicated with synthetic hypotensive drugs without monitoring.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Alstonia macrophylla).',
  },
  {
    localName: 'Bayag-usa',
    scientificName: 'Voacanga globosa',
    cebuanoName: 'Bita-bita',
    englishName: 'Philippine Voacanga',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Latex used as a toothache soother; bark decoction used as an antiseptic wash for stubborn ulcers.',
    preparationMethod: 'Apply a small dab of latex on a cotton pellet directly into carious tooth cavity.',
    dosage: 'Apply topically for 10 minutes for acute toothache. Spit out saliva.',
    warnings: 'Toxic if swallowed in large quantities: for topical dental application only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Voacanga globosa).',
  },
  {
    localName: 'Bikas',
    scientificName: 'Mikania cordata',
    cebuanoName: 'Ubi-ubihan',
    englishName: 'Heartleaf Hempvine',
    category: 'Wound Care & Astringent',
    medicinalUses: 'Pounded fresh leaves applied directly as a potent hemostatic poultice on fresh cuts and venomous insect bites.',
    preparationMethod: 'Crush clean fresh leaves thoroughly to release green juice and apply directly over the wound.',
    dosage: 'Apply poultice for 15-30 minutes. Bind with clean cloth.',
    warnings: 'Clean wound thoroughly with antiseptic water before application.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Mikania cordata).',
  },
  {
    localName: 'Binunga',
    scientificName: 'Macaranga tanarius',
    cebuanoName: 'Binonga',
    englishName: 'Elephant Ear Tree / Blush Macaranga',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Astringent bark and leaf decoction used as a gargle for mouth ulcers, sore throat, and to wash fungal skin sores.',
    preparationMethod: 'Boil 10g bark or 5 large leaves in 3 cups of water for 15 minutes.',
    dosage: 'Gargle warm liquid 3 times daily; use as skin wash twice daily.',
    warnings: 'Safe for topical gargle and wash. Do not swallow large concentrated quantities.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Macaranga tanarius).',
  },
  {
    localName: 'Bogo',
    scientificName: 'Garuga floribunda',
    cebuanoName: 'Bogo-kahoy',
    englishName: 'Garuga Tree',
    category: 'Respiratory',
    medicinalUses: 'Bark decoction used for asthma, bronchial cough, and cooling pulmonary congestion; leaf juice for eye irritation.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Prepare fresh decoctions daily; avoid in pregnant patients.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Garuga floribunda).',
  },
  {
    localName: 'Buntot-pusa',
    scientificName: 'Acalypha hispida',
    cebuanoName: 'Ikog-iring',
    englishName: 'Chenille Plant / Red Hot Cat\'s Tail',
    category: 'Renal & Diuretic',
    medicinalUses: 'Floral spikes and leaves boiled as a diuretic, expectorant for asthma, and soothing wash for skin rashes.',
    preparationMethod: 'Boil 10g floral spikes in 2 cups of water for 10 minutes.',
    dosage: 'Drink 1/2 cup twice daily; use as topical wash for rashes.',
    warnings: 'Ingestion of excessive raw leaves can cause mild stomach upset.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Acalypha hispida).',
  },
  {
    localName: 'Buyo-buyo',
    scientificName: 'Piper sarmentosum',
    cebuanoName: 'Kudok-kudok',
    englishName: 'Wild Betel Leaf / Lolot',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Aromatic leaves chewed or brewed for stomach ache, toothache, flatulence, and pleurisy.',
    preparationMethod: 'Steep 5 fresh leaves in 1 cup of boiling water for 10 minutes.',
    dosage: 'Drink 1 cup warm after meals for indigestion.',
    warnings: 'Safe culinary green. Moderation recommended for individuals prone to calcium oxalate kidney stones.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Piper sarmentosum).',
  },
  {
    localName: 'Dadap',
    scientificName: 'Erythrina variegata',
    cebuanoName: 'Dapdap',
    englishName: 'Tiger\'s Claw / Indian Coral Tree',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Leaves and bark poultice applied to relieve joint inflammation, rheumatic pain, and insomnia.',
    preparationMethod: 'Warm bruised fresh leaves over coals and wrap around painful joints.',
    dosage: 'Apply warm leaf compress twice daily for 20 minutes.',
    warnings: 'Contains alkaloids: strictly avoid ingesting raw seeds or concentrated bark extracts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Erythrina variegata).',
  },
  {
    localName: 'Dampol',
    scientificName: 'Glochidion album',
    cebuanoName: 'Bagnay-pula',
    englishName: 'White Glochidion',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Bark and leaf decoctions used as an astringent rinse for sore gums, throat inflammation, and skin eczema.',
    preparationMethod: 'Boil 10g dried leaves in 2 cups of water for 15 minutes. Cool and strain.',
    dosage: 'Use as mouth rinse or skin wash 2-3 times daily.',
    warnings: 'External rinse preferred. May cause mild nausea if ingested in high amounts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Glochidion album).',
  },
  {
    localName: 'Dilang-aso',
    scientificName: 'Elephantopus scaber',
    cebuanoName: 'Tabataba',
    englishName: 'Elephant\'s Foot',
    category: 'Renal & Diuretic',
    medicinalUses: 'Plant decoction taken as a diuretic to treat edema, urinary discomfort, fevers, and post-partum recovery.',
    preparationMethod: 'Boil 10g whole dried plant in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Consult healthcare practitioner if taking prescription diuretic drugs.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Elephantopus scaber).',
  },
  {
    localName: 'Dita-ditahan',
    scientificName: 'Rauvolfia serpentina',
    cebuanoName: 'Indian Snakeroot',
    englishName: 'Serpentine Wood',
    category: 'Cardiovascular (Strict Warnings)',
    medicinalUses: 'Historically documented source of reserpine, used for severe hypertension and nervous restlessness.',
    preparationMethod: 'Strict medical standardization required: raw home brewing is not advised due to potent hypotension risks.',
    dosage: 'Use strictly under qualified clinical supervision.',
    warnings: 'POTENT MEDICATION: Causes severe bradycardia, mental depression, and hypotension. Never self-prescribe.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Rauvolfia serpentina).',
  },
  {
    localName: 'Dita-kanding',
    scientificName: 'Alstonia spectabilis',
    cebuanoName: 'Dita-gamay',
    englishName: 'Mountain Dita',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Bark decoction traditionally used as an antimalarial, fever remedy, and bitter digestive tonic.',
    preparationMethod: 'Boil 5g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily for fever.',
    warnings: 'Do not exceed recommended dose; avoid in pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Alstonia spectabilis).',
  },
  {
    localName: 'Dungon',
    scientificName: 'Heritiera littoralis',
    cebuanoName: 'Dungun',
    englishName: 'Looking-glass Mangrove',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Tannin-rich seed and bark extract used for diarrhea, dysentery, and as a mouthwash for toothache.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily for diarrhea; use as oral rinse for toothache.',
    warnings: 'Astringent: avoid excessive consumption.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Heritiera littoralis).',
  },
  {
    localName: 'Dungon-late',
    scientificName: 'Heritiera sylvatica',
    cebuanoName: 'Dungun-ilahas',
    englishName: 'Inland Dungon',
    category: 'Wound Care & Astringent',
    medicinalUses: 'Bark decoction applied to clean bleeding wounds, ulcers, and hemorrhoids.',
    preparationMethod: 'Boil 15g bark in 3 cups of water for 20 minutes. Use as warm wash.',
    dosage: 'Rinse affected area twice daily.',
    warnings: 'For topical cleansing and wash only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Heritiera sylvatica).',
  },
  {
    localName: 'Gagabutan',
    scientificName: 'Eleusine indica',
    cebuanoName: 'Paragis',
    englishName: 'Goosegrass / Wiregrass',
    category: 'Renal & Diuretic',
    medicinalUses: 'Whole plant decoction extensively used in Philippine folk medicine for diuretic support, kidney stone clearance, fevers, and cystitis.',
    preparationMethod: 'Boil 50g cleaned whole plant (including roots) in 1 liter of water for 15 minutes. Strain.',
    dosage: 'Drink 1 cup 2-3 times daily for urinary comfort.',
    warnings: 'Mild diuretic. Not a replacement for emergency dialysis or acute kidney care.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Eleusine indica) & Philippine Folk Ethnobotany.',
  },
  {
    localName: 'Gatas-gatas',
    scientificName: 'Euphorbia thymifolia',
    cebuanoName: 'Makikitot',
    englishName: 'Gulf Sandmat / Chickenweed',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Astringent whole plant tea used for dysentery, diarrhea in children, and ringworm poultice.',
    preparationMethod: 'Boil 10g fresh plant in 1.5 cups of water for 10 minutes.',
    dosage: 'Drink 1/3 cup twice daily for mild diarrhea.',
    warnings: 'Contains milky latex: discontinue if gastric burning or nausea occurs.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Euphorbia thymifolia).',
  },
  {
    localName: 'Gumamela-asul',
    scientificName: 'Hibiscus syriacus',
    cebuanoName: 'Rose of Sharon',
    englishName: 'Blue Hibiscus / Rose of Sharon',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Flowers and leaves boiled as a demulcent, soothing irritated skin, boils, and reducing feverish thirst.',
    preparationMethod: 'Crush fresh flower petals into a paste and apply over skin boils; or infuse in warm water.',
    dosage: 'Apply petal poultice for 20 minutes twice daily.',
    warnings: 'Safe emollient. Wash flowers clean of dust before use.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Hibiscus syriacus).',
  },
  {
    localName: 'Guyod',
    scientificName: 'Derris elliptica',
    cebuanoName: 'Tubli',
    englishName: 'Poison Vine / Derris Root',
    category: 'Dermatological (Caution)',
    medicinalUses: 'Diluted root extract historically applied externally for severe scabies, lice, and cutaneous parasites.',
    preparationMethod: 'Extract root juice and dilute heavily with coconut oil for topical scalp rinse.',
    dosage: 'Apply to affected area for 15 minutes, then shampoo thoroughly. Avoid eyes and mouth.',
    warnings: 'HIGHLY TOXIC (Rotenone): Lethal if ingested. Toxic to aquatic life. Strictly external use with gloves.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Derris elliptica).',
  },
  {
    localName: 'Hagakhak',
    scientificName: 'Dipterocarpus kerrii',
    cebuanoName: 'Hagakhak-pula',
    englishName: 'Keruing Tree',
    category: 'Respiratory',
    medicinalUses: 'Aromatic wood resin historically used in chest plasters and vapors for chronic bronchitis and ulcers.',
    preparationMethod: 'Inhale steam infused with a small piece of resin, or apply resin-infused oil topically on chest.',
    dosage: 'Steam inhalation for 10 minutes once daily before sleep.',
    warnings: 'Do not ingest raw resin. Discontinue if bronchial irritation increases.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Dipterocarpus kerrii).',
  },
  {
    localName: 'Hamindang',
    scientificName: 'Macaranga bicolor',
    cebuanoName: 'Binunga-bicolor',
    englishName: 'Two-color Macaranga',
    category: 'Wound Care & Astringent',
    medicinalUses: 'Bark and leaf decoction used as an astringent antiseptic wash for chronic sores and postpartum healing.',
    preparationMethod: 'Boil 10g dried leaves in 2 cups of water for 15 minutes.',
    dosage: 'Apply as warm wash twice daily over affected skin.',
    warnings: 'For topical use only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Macaranga bicolor).',
  },
  {
    localName: 'Hangod',
    scientificName: 'Laportea meyeniana',
    cebuanoName: 'Lipa-meyeni',
    englishName: 'Poison Nettle Tree',
    category: 'Pain Relief & Anti-inflammatory (Caution)',
    medicinalUses: 'Carefully administered traditional counter-irritant for chronic rheumatic pain; boiled roots for epistaxis.',
    preparationMethod: 'Boil 5g cleaned roots in 2 cups of water for 10 minutes for nosebleeds.',
    dosage: 'Drink 1/4 cup decoction once daily.',
    warnings: 'Leaves have severe stinging hairs that cause acute burning pain and dermatitis. Handle with heavy gloves.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Laportea meyeniana).',
  },
  {
    localName: 'Hauili',
    scientificName: 'Ficus septica',
    cebuanoName: 'Labnog',
    englishName: 'Seven Golden Fig',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Leaves applied as a poultice on rheumatic joints and headache; milky sap applied to herpes, boils, and ringworm.',
    preparationMethod: 'Wilt fresh leaves over low heat and apply as a warm poultice to the forehead or joints.',
    dosage: 'Apply for 30 minutes twice daily.',
    warnings: 'Sap can cause contact dermatitis in sensitive skin. Wash hands after handling.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ficus septica).',
  },
  {
    localName: 'Hibau',
    scientificName: 'Aglaia harmsiana',
    cebuanoName: 'Malasaging',
    englishName: 'Harms Aglaia',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Bark decoction traditionally used by indigenous healers for fevers, chills, and restoring physical vigor.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily.',
    warnings: 'Use in moderation; avoid during pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Aglaia harmsiana).',
  },
  {
    localName: 'Iba',
    scientificName: 'Phyllanthus acidus',
    cebuanoName: 'Karamay',
    englishName: 'Otaheite Gooseberry / Star Gooseberry',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Leaves boiled as an antipruritic wash for urticaria, eczema, and psoriasis; bark used for bronchial congestion.',
    preparationMethod: 'Boil a handful of leaves in 3 cups of water for 15 minutes. Use cooled liquid as skin bath.',
    dosage: 'Wash affected skin 1-2 times daily.',
    warnings: 'Roots are toxic and must never be consumed. Leaves and fruit are safe.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Phyllanthus acidus).',
  },
  {
    localName: 'Inyam',
    scientificName: 'Antidesma ghaesembilla',
    cebuanoName: 'Binayuyu',
    englishName: 'Black Currant Tree',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Aromatic leaves and fruit decoction taken for fevers, headache, and as a digestive appetizer.',
    preparationMethod: 'Boil 10g leaves in 2 cups of water for 10 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Safe in standard dietary amounts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Antidesma ghaesembilla).',
  },
  {
    localName: 'Kaburaw',
    scientificName: 'Citrus hystrix',
    cebuanoName: 'Kolobot',
    englishName: 'Kaffir Lime / Makrut Lime',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Rind and leaves rich in citronellal: used for oral hygiene, shampoo for dandruff, and digestive carminative.',
    preparationMethod: 'Rub fresh fruit rind or juice onto scalp for dandruff; steep leaves for digestive tea.',
    dosage: 'Scalp rinse 2-3 times a week; drink 1/2 cup leaf tea after heavy meals.',
    warnings: 'Citrus juice may cause photosensitivity if left exposed to bright sunlight.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Citrus hystrix).',
  },
  {
    localName: 'Kalabasa',
    scientificName: 'Cucurbita moschata',
    cebuanoName: 'Kalabasa-pula',
    englishName: 'Squash / Pumpkin',
    category: 'Digestive & Parasitic',
    medicinalUses: 'Fresh seeds are an effective, safe natural anthelmintic (cucurbitacin) against tapeworms and roundworms; fruit pulp soothes burns.',
    preparationMethod: 'Crush 30-50g peeled raw seeds into a paste with honey or water and consume on an empty stomach.',
    dosage: 'Take once in the morning, followed 2 hours later by a mild natural laxative (e.g., castor oil or prune juice).',
    warnings: 'Safe and gentle. Ensure seeds are unsalted and unroasted for anthelmintic efficacy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Cucurbita moschata) & DOH PNF.',
  },
  {
    localName: 'Kalamias-gubat',
    scientificName: 'Ailanthus triphysa',
    cebuanoName: 'Malabalite',
    englishName: 'White Bean Tree',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Bitter resinous bark used for dyspepsia, diarrhea, and asthma; aromatic resin burned as soothing incense.',
    preparationMethod: 'Boil 5g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily before meals.',
    warnings: 'Bitter: excessive doses cause nausea. Avoid in pregnant women.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ailanthus triphysa).',
  },
  {
    localName: 'Kalatsutsing-gubat',
    scientificName: 'Tabernaemontana pandacaqui',
    cebuanoName: 'Pandakaki-puti',
    englishName: 'Windmill Bush',
    category: 'Wound Care & Hemostatic',
    medicinalUses: 'Milky sap and leaf poultice applied to stop bleeding, disinfect lacerations, and relieve toothache.',
    preparationMethod: 'Pound fresh leaves into a poultice and bind over cuts; drop sap on sterile gauze for minor scrapes.',
    dosage: 'Apply topically once daily.',
    warnings: 'External use only. Avoid ingestion; keep away from eyes.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Tabernaemontana pandacaqui).',
  },
  {
    localName: 'Kalios',
    scientificName: 'Streblus asper',
    cebuanoName: 'Bogos',
    englishName: 'Toothbrush Tree / Sandpaper Tree',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Twigs traditionally chewed for dental hygiene and toothache relief; bark decoction used for dysentery and gingivitis.',
    preparationMethod: 'Boil 10g shredded bark in 2 cups of water for 15 minutes. Use cooled liquid as antibacterial mouthwash.',
    dosage: 'Gargle 1/4 cup 3 times daily after brushing.',
    warnings: 'Demonstrated antibacterial efficacy against Streptococcus mutans. Do not swallow large amounts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Streblus asper).',
  },
  {
    localName: 'Kalumpit',
    scientificName: 'Terminalia microcarpa',
    cebuanoName: 'Alupi',
    englishName: 'Kalumpit Tree',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Astringent fruit and bark decoction used for throat inflammation, eye wash, and chronic diarrhea.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes.',
    dosage: 'Gargle 3 times daily; drink 1/4 cup twice daily for diarrhea.',
    warnings: 'Rich in tannins: avoid prolonged continuous consumption.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Terminalia microcarpa).',
  },
  {
    localName: 'Kamagsa',
    scientificName: 'Rourea minor',
    cebuanoName: 'Gikos-gikos',
    englishName: 'Small-leaved Rourea',
    category: 'Postpartum & Rheumatic',
    medicinalUses: 'Root decoction used by traditional midwives as a depurative and tonic after childbirth.',
    preparationMethod: 'Boil 10g cleaned roots in 3 cups of water for 20 minutes.',
    dosage: 'Drink 1/3 cup twice daily for 3 days postpartum.',
    warnings: 'Do NOT use during active pregnancy: possesses uterine stimulating properties.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Rourea minor).',
  },
  {
    localName: 'Kamas',
    scientificName: 'Pachyrhizus erosus',
    cebuanoName: 'Singkamas',
    englishName: 'Jicama / Yam Bean',
    category: 'Dermatological & Hydration',
    medicinalUses: 'Cooling tuber slices applied on sunburnt skin, prickly heat, and feverish brows; high water and inulin content.',
    preparationMethod: 'Apply freshly sliced chilled tuber directly to sunburnt skin or blend into cooling face mask.',
    dosage: 'Apply for 15-20 minutes as needed.',
    warnings: 'Only the tuber is edible/medicinal. Seeds, leaves, and pods contain toxic rotenone and are dangerous.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pachyrhizus erosus).',
  },
  {
    localName: 'Kamatsile',
    scientificName: 'Pithecellobium dulce',
    cebuanoName: 'Kamonsil',
    englishName: 'Manila Tamarind',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Astringent bark and leaf decoction used for mouth ulcers, toothache, dysentery, and washing chronic sores.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes. Use for mouth rinse or wash.',
    dosage: 'Rinse mouth 3 times daily; drink 1/4 cup twice daily for mild diarrhea.',
    warnings: 'High tannin content. Avoid excessive internal consumption.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pithecellobium dulce).',
  },
  {
    localName: 'Kanya-pistula',
    scientificName: 'Cassia fistula',
    cebuanoName: 'Ibihas',
    englishName: 'Golden Shower / Purging Cassia',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Ripe pod pulp used as a safe, mild laxative for habitual constipation; leaves applied on ringworm.',
    preparationMethod: 'Dissolve 5-10g of black pod pulp in warm water or milk.',
    dosage: 'Take at bedtime for constipation.',
    warnings: 'Do not exceed 15g to avoid abdominal cramping. Contraindicated in bowel obstruction.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Cassia fistula).',
  },
  {
    localName: 'Kariskis',
    scientificName: 'Albizia lebbekoides',
    cebuanoName: 'Haluganay',
    englishName: 'Forest Siris',
    category: 'Respiratory',
    medicinalUses: 'Bark decoction used for persistent cough, bronchitis, and as an astringent wash for scabies.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/3 cup twice daily for bronchial cough.',
    warnings: 'Safe in moderate traditional doses.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Albizia lebbekoides).',
  },
  {
    localName: 'Katilbuk',
    scientificName: 'Impatiens platypetala',
    cebuanoName: 'Kamantigue-bukid',
    englishName: 'Wild Balsam',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Crushed succulent stems and leaves applied to minor thermal burns, scalds, and insect stings.',
    preparationMethod: 'Crush clean stems to extract cooling gelatinous juice and apply to unbroken skin.',
    dosage: 'Apply topically every 2 hours until burning sensation subsides.',
    warnings: 'For superficial burns only; do not apply to open 3rd-degree burns.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Impatiens platypetala).',
  },
  {
    localName: 'Katutay',
    scientificName: 'Bauhinia purpurea',
    cebuanoName: 'Alibangbang-pula',
    englishName: 'Purple Orchid Tree',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Astringent bark and flower decoction used as a gargle for sore throat, tonsillitis, and ulcers.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Gargle warm liquid 3 times daily.',
    warnings: 'Non-toxic gargle; avoid consuming excessive quantities.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Bauhinia purpurea).',
  },
  {
    localName: 'Kayoman',
    scientificName: 'Ficus ulmifolia',
    cebuanoName: 'Isis',
    englishName: 'Elm-leaved Fig',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Rough sandpaper-like leaves used for dental hygiene; leaf decoction used for washing ringworm and cuts.',
    preparationMethod: 'Boil a handful of leaves in 2 cups of water for 10 minutes. Use as topical wash.',
    dosage: 'Wash affected skin twice daily.',
    warnings: 'Gentle antiseptic wash; avoid contact with sensitive mucosal tissues.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ficus ulmifolia).',
  },
  {
    localName: 'Kolowratia',
    scientificName: 'Alpinia elegans',
    cebuanoName: 'Tagbak',
    englishName: 'Elegant Galangal',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Aromatic rhizomes and leaves pounded and applied as a warm poultice for rheumatism, muscle aches, and headache.',
    preparationMethod: 'Crush fresh rhizome and warm with coconut oil; apply as poultice over stiff joints.',
    dosage: 'Apply once daily for 30 minutes.',
    warnings: 'For external use; perform patch test on sensitive skin.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Alpinia elegans).',
  },
  {
    localName: 'Kubili',
    scientificName: 'Cubilia cubili',
    cebuanoName: 'Kamut-kabayo',
    englishName: 'Philippine Cubilia',
    category: 'Nutritional & General Wellness',
    medicinalUses: 'Boiled seeds are nourishing and soothing for gastrointestinal catarrh and convalescent recovery.',
    preparationMethod: 'Boil peeled seeds thoroughly in water until tender.',
    dosage: 'Eat 5-10 boiled seeds as nutritional supplement.',
    warnings: 'Must be boiled thoroughly before consumption.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Cubilia cubili).',
  },
  {
    localName: 'Kudzu-gubat',
    scientificName: 'Pueraria phaseoloides',
    cebuanoName: 'Kudzu-ilahas',
    englishName: 'Tropical Kudzu',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Leaf decoction applied as a soothing wash for boils, infected skin eruptions, and ulcerations.',
    preparationMethod: 'Boil 20g fresh leaves in 3 cups of water for 15 minutes.',
    dosage: 'Wash affected skin surfaces twice daily.',
    warnings: 'Topical use recommended.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pueraria phaseoloides).',
  },
  {
    localName: 'Kulipapa',
    scientificName: 'Vitex parviflora',
    cebuanoName: 'Molave',
    englishName: 'Molave Tree',
    category: 'Wound Care & Astringent',
    medicinalUses: 'Astringent wood infusion and bark decoction used as a wound wash, febrifuge, and poison antidote wash.',
    preparationMethod: 'Boil 10g dried wood chips or bark in 2 cups of water for 20 minutes.',
    dosage: 'Use as wound wash twice daily; drink 1/4 cup twice daily for fevers.',
    warnings: 'Protected indigenous tree; harvest only sustainably fallen wood or pruned branches.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Vitex parviflora).',
  },
  {
    localName: 'Kulitis-parang',
    scientificName: 'Celosia argentea',
    cebuanoName: 'Kadiliyo',
    englishName: 'Cockscomb / Silver Cockscomb',
    category: 'Renal & Diuretic',
    medicinalUses: 'Seeds and flowers brewed to clear heat, promote urination, soothe eye inflammation, and relieve painful micturition.',
    preparationMethod: 'Boil 10g dried seeds or floral heads in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Mild hypotensive effect. Caution in patients with glaucoma (mydriatic effect).',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Celosia argentea).',
  },
  {
    localName: 'Lagundi-dagat',
    scientificName: 'Vitex trifolia',
    cebuanoName: 'Dangla-baybay',
    englishName: 'Simpleleaf Chastetree / Coastal Vitex',
    category: 'Respiratory',
    medicinalUses: 'Coastal relative of Lagundi: leaves boiled for cough, fever, headache, and rheumatic muscle pains.',
    preparationMethod: 'Boil 8-10 leaves in 2 cups of water for 15 minutes. Strain.',
    dosage: 'Drink 1/2 cup 3 times daily for cough.',
    warnings: 'Avoid excessive intake during pregnancy. Similar profile to Vitex negundo.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Vitex trifolia).',
  },
  {
    localName: 'Lamio',
    scientificName: 'Dracontomelon dao',
    cebuanoName: 'Dao',
    englishName: 'Pacific Walnut / Dao Tree',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Bark decoction used as an astringent for dysentery and diarrhea, and topically for cicatrizing sores.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily for acute diarrhea.',
    warnings: 'High in tannins: not for long-term daily use.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Dracontomelon dao).',
  },
  {
    localName: 'Libas',
    scientificName: 'Spondias pinnata',
    cebuanoName: 'Alubihon',
    englishName: 'Wild Hog Plum',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Bark and leaves boiled for acute diarrhea, dysentery, mouth ulcers, and poulticed over burns.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes. Cool before drinking or gargling.',
    dosage: 'Drink 1/3 cup twice daily for diarrhea; gargle for mouth sores.',
    warnings: 'Safe astringent; reduce dose once diarrhea subsides.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Spondias pinnata).',
  },
  {
    localName: 'Ligao',
    scientificName: 'Ziziphus talanai',
    cebuanoName: 'Talanay',
    englishName: 'Philippine Jujube',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Bark decoction used as an astringent stomachic, diarrhea remedy, and febrifuge.',
    preparationMethod: 'Boil 10g dried shredded bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/3 cup twice daily.',
    warnings: 'Safe in standard traditional amounts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ziziphus talanai).',
  },
  {
    localName: 'Linti',
    scientificName: 'Gnetum gnemon',
    cebuanoName: 'Bago',
    englishName: 'Melinjo / Gnetum',
    category: 'Nutritional & General Wellness',
    medicinalUses: 'High resveratrol content: leaves and nuts eaten for antioxidant protection, eye comfort, and physical endurance.',
    preparationMethod: 'Boil young leaves and seeds in vegetable soups or decoct 15g leaves in 2 cups of water.',
    dosage: 'Consume as dietary vegetable 2-3 times weekly; drink 1 cup leaf tea.',
    warnings: 'Individuals with hyperuricemia (gout) should consume seeds in moderation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Gnetum gnemon).',
  },
  {
    localName: 'Lumbang',
    scientificName: 'Aleurites moluccanus',
    cebuanoName: 'Biaw',
    englishName: 'Candlenut Tree',
    category: 'Dermatological & Scalp',
    medicinalUses: 'Expressed seed oil applied to stimulate hair growth, treat dandruff, and as a strong purgative (caution).',
    preparationMethod: 'Apply cold-pressed candlenut oil directly to scalp; massage gently.',
    dosage: 'Apply to hair and scalp 2 times weekly, leave for 30 minutes, then wash.',
    warnings: 'Raw seeds are TOXIC and purgative. Do NOT ingest raw nuts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Aleurites moluccanus).',
  },
  {
    localName: 'Lunas',
    scientificName: 'Lunasia amara',
    cebuanoName: 'Lunas-bundok',
    englishName: 'Bitter Lunasia',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Extremely bitter bark and leaves used as a digestive stomachic, febrifuge, and topical snakebite poultice.',
    preparationMethod: 'Boil 3-5g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 2 tablespoons before meals for stomachic stimulation.',
    warnings: 'Contains lunasine and potent alkaloids. Strict dosage adherence required. Do not use in pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Lunasia amara).',
  },
  {
    localName: 'Lupa',
    scientificName: 'Boehmeria nivea',
    cebuanoName: 'Amirai',
    englishName: 'Ramie',
    category: 'Renal & Diuretic',
    medicinalUses: 'Roots and leaves decocted as a diuretic, cooling febrifuge, and hemostatic for threatened miscarriage.',
    preparationMethod: 'Boil 15g roots in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Consult healthcare provider for obstetric complications.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Boehmeria nivea).',
  },
  {
    localName: 'Malabulak',
    scientificName: 'Bombax ceiba',
    cebuanoName: 'Salay',
    englishName: 'Red Silk Cotton Tree',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Astringent resin and gum (mocharas) used for dysentery, diarrhea, hemoptysis, and skin burns.',
    preparationMethod: 'Boil 5g dried bark or resin in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/3 cup twice daily for diarrhea.',
    warnings: 'Astringent: use for short durations during acute bowel looseness.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Bombax ceiba).',
  },
  {
    localName: 'Malunggay-gubat',
    scientificName: 'Radermachera pinnata',
    cebuanoName: 'Bannay-bannay',
    englishName: 'Forest Radermachera',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Bark decoction used by indigenous mountain communities as an antipyretic tonic and body ache soother.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily.',
    warnings: 'Avoid in pregnancy; prepare fresh daily.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Radermachera pinnata).',
  },
  {
    localName: 'Mamalis',
    scientificName: 'Pittosporum pentandrum',
    cebuanoName: 'Duting-bato',
    englishName: 'Taiwanese Cheesewood',
    category: 'Fevers & Postpartum',
    medicinalUses: 'Aromatic bark decoction given as a febrifuge and in aromatic baths for women recovering from childbirth.',
    preparationMethod: 'Boil 10g bark in 3 cups of water for 20 minutes for postpartum herbal bath.',
    dosage: 'Drink 1/4 cup decoction twice daily for fever; use warm bath water daily.',
    warnings: 'Aromatic principles may cause nausea if taken in large doses on an empty stomach.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pittosporum pentandrum).',
  },
  {
    localName: 'Marang',
    scientificName: 'Artocarpus odoratissimus',
    cebuanoName: 'Marang-tam-is',
    englishName: 'Marang / Johey Oak',
    category: 'Nutritional & General Wellness',
    medicinalUses: 'Nutrient-dense fruit pulp provides rich energy, potassium, and demulcent fiber for convalescent individuals.',
    preparationMethod: 'Eat fresh ripe fruit segments directly.',
    dosage: '1-2 servings daily as nutritional recovery food.',
    warnings: 'High in natural sugars: diabetic patients should consume in controlled portions.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Artocarpus odoratissimus).',
  },
  {
    localName: 'Mirasol',
    scientificName: 'Helianthus annuus',
    cebuanoName: 'Mirasol-dalag',
    englishName: 'Sunflower',
    category: 'Renal & Diuretic',
    medicinalUses: 'Seed decoction taken as a gentle diuretic, expectorant for bronchial coughs, and febrifuge.',
    preparationMethod: 'Boil 20g crushed seeds in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Safe and gentle. Shell seeds before decocting.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Helianthus annuus).',
  },
  {
    localName: 'Nangka-nangka',
    scientificName: 'Annona glabra',
    cebuanoName: 'Pond Apple',
    englishName: 'Pond Apple / Alligator Apple',
    category: 'Dermatological (Caution)',
    medicinalUses: 'Seeds and leaves traditionally used as an external pediculicide (lice killer) and parasitic skin wash.',
    preparationMethod: 'Boil leaves in water for external antiparasitic wash.',
    dosage: 'Apply to scalp or skin for 15 minutes, then rinse thoroughly.',
    warnings: 'Seeds contain toxic annonaceous acetogenins. Do NOT ingest seeds.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Annona glabra).',
  },
  {
    localName: 'Ngipin-ngipin',
    scientificName: 'Pseudarthria viscida',
    cebuanoName: 'Maniy-maniy',
    englishName: 'Sticky Desmodium cousin',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Roots boiled to treat rheumatism, chronic fever, asthma, and nerve weakness.',
    preparationMethod: 'Boil 10g dried roots in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Safe in standard traditional amounts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pseudarthria viscida).',
  },
  {
    localName: 'Pahutan',
    scientificName: 'Mangifera altissima',
    cebuanoName: 'Paho',
    englishName: 'Wild Mango',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Astringent bark and seed kernel decoctions used for dysentery, diarrhea, and aphthous stomatitis.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes. Use for mouth rinse or drink.',
    dosage: 'Gargle 3 times daily; drink 1/4 cup twice daily for diarrhea.',
    warnings: 'Astringent tannins: discontinue when diarrhea resolves.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Mangifera altissima).',
  },
  {
    localName: 'Palasan',
    scientificName: 'Calamus merrillii',
    cebuanoName: 'Uway',
    englishName: 'Philippine Rattan',
    category: 'Ophthalmic & Dermatological',
    medicinalUses: 'Clear stem sap dripped into eyes for redness and conjunctival heat; root decoction for chronic skin sores.',
    preparationMethod: 'Collect fresh sterile exudate from freshly cut vine stem and apply with sterile dropper.',
    dosage: '1 drop in irritated eye once daily; or wash sores with root decoction.',
    warnings: 'Ensure absolute cleanliness of collection point to avoid secondary eye infection.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Calamus merrillii).',
  },
  {
    localName: 'Palawan',
    scientificName: 'Cyrtosperma merkusii',
    cebuanoName: 'Palaw',
    englishName: 'Giant Swamp Taro',
    category: 'Nutritional & Demulcent',
    medicinalUses: 'Starchy corm boiled as a gentle demulcent food for gastric irritation and convalescence.',
    preparationMethod: 'Boil corm thoroughly in multiple changes of water until soft to eliminate calcium oxalate raphides.',
    dosage: 'Eat boiled corm as mild digestible starch.',
    warnings: 'Must be cooked thoroughly to neutralize acrid calcium oxalate crystals.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Cyrtosperma merkusii).',
  },
  {
    localName: 'Pandakaki',
    scientificName: 'Tabernaemontana divaricata',
    cebuanoName: 'Pandakaki-doble',
    englishName: 'Crape Jasmine / Pinwheel Flower',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Milky sap applied to wounds to prevent infection; root decoction chewed for toothache relief.',
    preparationMethod: 'Crush leaves into a poultice or apply dab of milky sap directly onto minor abrasions.',
    dosage: 'Apply topically once daily.',
    warnings: 'For external use only. Ingestion of raw plant causes nausea and sedation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Tabernaemontana divaricata).',
  },
  {
    localName: 'Pangi',
    scientificName: 'Pangium edule',
    cebuanoName: 'Pangi-kahoy',
    englishName: 'Football Fruit Tree',
    category: 'Dermatological (Caution)',
    medicinalUses: 'Boiled leaves used strictly as an antiseptic wash for stubborn skin parasites and maggot-infested wounds.',
    preparationMethod: 'Boil clean leaves in water for 15 minutes. Use cooled liquid strictly as an external wash.',
    dosage: 'Wash affected skin once daily.',
    warnings: 'HIGHLY TOXIC (Hydrogen cyanide in raw seeds): Seeds are deadly without extensive fermentation. Never ingest raw seeds.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pangium edule).',
  },
  {
    localName: 'Pasau',
    scientificName: 'Corchorus olitorius',
    cebuanoName: 'Saluyot-haba',
    englishName: 'Jute Mallow / Nalta Jute',
    category: 'Nutritional & General Wellness',
    medicinalUses: 'Mucilaginous leaves provide rich iron, calcium, demulcent protection for gastric mucosa, and mild laxative action.',
    preparationMethod: 'Cook fresh leaves into broth or steep 10g dried leaves in 1 cup boiling water.',
    dosage: 'Eat in meals or drink 1 cup leaf tea daily.',
    warnings: 'Safe and wholesome nutritional green.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Corchorus olitorius) & DOH PNF.',
  },
  {
    localName: 'Pastores',
    scientificName: 'Euphorbia pulcherrima',
    cebuanoName: 'Pascua',
    englishName: 'Poinsettia',
    category: 'Dermatological (Caution)',
    medicinalUses: 'Folk poultice of crushed leaves applied to erysipelas and skin swellings.',
    preparationMethod: 'Crush clean leaves and apply topically over closed swelling with sterile bandage.',
    dosage: 'Apply for 15 minutes once daily.',
    warnings: 'Milky sap is irritating to skin and mucous membranes. Never ingest.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Euphorbia pulcherrima).',
  },
  {
    localName: 'Pata',
    scientificName: 'Bauhinia acuminata',
    cebuanoName: 'Alibangbang-puti',
    englishName: 'White Orchid Tree / Snowy Orchid',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Leaves and bark boiled as a wash for skin diseases, ulcers, and gargled for throat catarrh.',
    preparationMethod: 'Boil 10g dried leaves in 2 cups of water for 15 minutes.',
    dosage: 'Wash affected skin twice daily; gargle for sore throat.',
    warnings: 'Safe topical wash. Discontinue if redness occurs.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Bauhinia acuminata).',
  },
  {
    localName: 'Pili',
    scientificName: 'Canarium ovatum',
    cebuanoName: 'Pili-kahoy',
    englishName: 'Pili Nut Tree',
    category: 'Nutritional & Dermatological',
    medicinalUses: 'Nutrient-rich kernel oil used as an emollient for dry skin; resin (Manila elemi) used in healing ointments for indolent ulcers.',
    preparationMethod: 'Apply cold-pressed pili nut oil directly to dry skin; refine resin into soothing balm.',
    dosage: 'Apply topically once daily.',
    warnings: 'Nut allergy warning for individuals allergic to tree nuts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Canarium ovatum).',
  },
  {
    localName: 'Pipisik',
    scientificName: 'Avicennia marina',
    cebuanoName: 'Api-api',
    englishName: 'Grey Mangrove',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Astringent bark and resin used topically for scabies, boils, ulcers, and chronic skin sores.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes. Use for cleansing skin sores.',
    dosage: 'Apply as wash twice daily.',
    warnings: 'External use only. Avoid open bleeding lacerations.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Avicennia marina).',
  },
  {
    localName: 'Rimas',
    scientificName: 'Artocarpus altilis',
    cebuanoName: 'Kolo',
    englishName: 'Breadfruit',
    category: 'Cardiovascular & Dermatological',
    medicinalUses: 'Yellowing leaf tea traditionally taken for mild hypertension; milky sap applied to skin infections and ringworm.',
    preparationMethod: 'Boil 1 fallen yellowed leaf in 4 cups of water for 15 minutes. Strain.',
    dosage: 'Drink 1/2 cup twice daily for mild blood pressure management.',
    warnings: 'Monitor blood pressure regularly. Do not discontinue prescribed hypertensive medications without physician guidance.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Artocarpus altilis).',
  },
  {
    localName: 'Siniguelas',
    scientificName: 'Spondias purpurea',
    cebuanoName: 'Sirkuelas',
    englishName: 'Spanish Plum / Red Mombin',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Bark and leaf decoctions used as an astringent rinse for sore throat, stomatitis, and acute diarrhea.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes.',
    dosage: 'Gargle warm liquid 3 times daily; drink 1/4 cup twice daily for diarrhea.',
    warnings: 'Safe astringent. Discontinue when diarrhea resolves.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Spondias purpurea).',
  },
  {
    localName: 'Saging',
    scientificName: 'Musa acuminata',
    cebuanoName: 'Saging-tindok',
    englishName: 'Banana',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Unripe green banana decoction is a potent astringent for acute diarrhea; sap applied to minor thermal burns.',
    preparationMethod: 'Boil 1 sliced green unripe banana in 2 cups of water for 10 minutes. Strain liquid.',
    dosage: 'Drink 1/2 cup every 4-6 hours for acute diarrhea.',
    warnings: 'Rich in pectin and resistant starch. Avoid in chronic constipation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Musa acuminata) & Philippine National Formulary.',
  },
  {
    localName: 'Salingbobog',
    scientificName: 'Crateva religiosa',
    cebuanoName: 'Balai-lamok',
    englishName: 'Sacred Garlic Pear',
    category: 'Renal & Diuretic',
    medicinalUses: 'Bark decoction used as a traditional lithontriptic for urinary gravel, burning urination, and fevers.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Stimulates urination: ensure sufficient water intake.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Crateva religiosa).',
  },
  {
    localName: 'Salomague-gubat',
    scientificName: 'Intsia bijuga',
    cebuanoName: 'Ipil',
    englishName: 'Moluccan Ironwood',
    category: 'Wound Care & Astringent',
    medicinalUses: 'Astringent bark decoction used as a cleansing wash for ulcers and relieving urinary catarrh.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Use as external wash; drink 1/4 cup once daily.',
    warnings: 'Protected hardwood tree; harvest only sustainably.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Intsia bijuga).',
  },
  {
    localName: 'Sinamay',
    scientificName: 'Musa textilis',
    cebuanoName: 'Abaka',
    englishName: 'Abaca / Manila Hemp',
    category: 'Wound Care & Astringent',
    medicinalUses: 'Root decoction used as an antiseptic wash for chronic ulcers; central stem pith sap applied on minor scalds.',
    preparationMethod: 'Boil 15g roots in 2 cups of water for 15 minutes for antiseptic wash.',
    dosage: 'Apply topically over clean gauze.',
    warnings: 'For topical use.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Musa textilis).',
  },
  {
    localName: 'Tangan-tangan',
    scientificName: 'Ricinus communis',
    cebuanoName: 'Lantang',
    englishName: 'Castor Bean / Castor Oil Plant',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Warmed fresh leaves applied as a poultice for rheumatic swellings and headaches; cold-pressed castor oil used for constipation.',
    preparationMethod: 'Warm fresh leaves over fire and bind over painful joints; or apply 1 teaspoon refined oil for constipation.',
    dosage: 'Topical poultice for 30 minutes; oral oil maximum 1 teaspoon for adults.',
    warnings: 'FATAL TOXICITY WARNING: Raw seeds contain ricin, a lethal cytotoxin. NEVER ingest raw seeds.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ricinus communis).',
  },
  {
    localName: 'Tagbak-gubat',
    scientificName: 'Alpinia haenkei',
    cebuanoName: 'Tagbak-dako',
    englishName: 'Haenke\'s Galangal',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Rhizome infusion taken for flatulence, indigestion, and as a warming tea for colds.',
    preparationMethod: 'Boil 10g sliced rhizome in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup warm after meals.',
    warnings: 'Avoid in acute peptic ulcer flare-ups.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Alpinia haenkei).',
  },
  {
    localName: 'Tambabalisa',
    scientificName: 'Cassia sophera',
    cebuanoName: 'Kasitas-gubat',
    englishName: 'Pepper Bush / Sophera Senna',
    category: 'Respiratory',
    medicinalUses: 'Bark and leaves boiled for bronchial asthma, bronchitis, and ringworm poultice.',
    preparationMethod: 'Boil 8-10 leaves in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily for bronchial spasms.',
    warnings: 'Mild laxative effect. Avoid in pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Cassia sophera).',
  },
  {
    localName: 'Tangisang-bayawak',
    scientificName: 'Ficus variegata',
    cebuanoName: 'Duoy',
    englishName: 'Variegated Fig',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Bark decoction and milky sap applied to boils, eczema, and skin inflammation.',
    preparationMethod: 'Apply a drop of fresh sap onto boils; or boil 10g bark for skin wash.',
    dosage: 'Apply topically once daily.',
    warnings: 'Sap may cause mild skin itching in sensitive individuals.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ficus variegata).',
  },
  {
    localName: 'Tawatawa-gubat',
    scientificName: 'Euphorbia heterophylla',
    cebuanoName: 'Painted Spurge',
    englishName: 'Fireplant / Wild Poinsettia',
    category: 'Dermatological (Caution)',
    medicinalUses: 'Crushed leaves traditionally applied on fungal skin infections and boils.',
    preparationMethod: 'Pound leaves into a poultice and apply over skin lesion.',
    dosage: 'Apply topically for 15 minutes.',
    warnings: 'Latex causes skin irritation. Do not ingest.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Euphorbia heterophylla).',
  },
  {
    localName: 'Tibig',
    scientificName: 'Ficus nota',
    cebuanoName: 'Tebeg',
    englishName: 'Salingbobog Fig',
    category: 'Renal & Diuretic',
    medicinalUses: 'Water exudate from severed young branches is a traditional refreshing drink that relieves feverish thirst and acts as a mild diuretic.',
    preparationMethod: 'Collect clear sap from freshly cut climbing branch into a clean container.',
    dosage: 'Drink 1/2 cup fresh once daily.',
    warnings: 'Ensure vine is identified correctly by an experienced local guide before consuming sap.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ficus nota).',
  },
  {
    localName: 'Tigbi',
    scientificName: 'Coix lacryma-jobi',
    cebuanoName: 'Adlay',
    englishName: 'Job\'s Tears / Adlay',
    category: 'Metabolic & Renal',
    medicinalUses: 'Grain decoction used as a gentle diuretic, metabolic tonic, joint pain reliever, and blood sugar regulator.',
    preparationMethod: 'Boil 30g hulled adlay grains in 3 cups of water for 25 minutes. Strain and drink the broth.',
    dosage: 'Drink 1 cup twice daily.',
    warnings: 'Wholesome gluten-free cereal. Traditional caution during early pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Coix lacryma-jobi) & DOH PNF.',
  },
  {
    localName: 'Timbangan',
    scientificName: 'Aristolochia tagala',
    cebuanoName: 'Kam-kam',
    englishName: 'Dutchman\'s Pipe / Tagala Vine',
    category: 'Fevers & Gastrointestinal (Caution)',
    medicinalUses: 'Extremely bitter root tonic historically used for malaria and snakebites.',
    preparationMethod: 'Historical remedy only: modern medical consensus advises against raw home preparations.',
    dosage: 'External poultice only under experienced supervision.',
    warnings: 'TOXIC WARNING: Contains aristolochic acid, which is nephrotoxic and carcinogenic. Ingestion is strictly prohibited.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Aristolochia tagala).',
  },
  {
    localName: 'Tolo-tolo',
    scientificName: 'Mallotus philippensis',
    cebuanoName: 'Banato',
    englishName: 'Kamala Tree',
    category: 'Digestive & Parasitic',
    medicinalUses: 'Red glandular hair powder from fruits (kamala) used as an effective vermifuge against tapeworms and for scabies.',
    preparationMethod: 'Mix 2-3g of fruit glandular powder with honey or coconut oil.',
    dosage: 'Take once in the morning on an empty stomach for intestinal parasites.',
    warnings: 'Potent purgative anthelmintic: do not exceed recommended dose.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Mallotus philippensis).',
  },
  {
    localName: 'Tuba',
    scientificName: 'Croton tiglium',
    cebuanoName: 'Tuba-tuba',
    englishName: 'Purging Croton',
    category: 'Dermatological (Strict Caution)',
    medicinalUses: 'Seed oil historically applied in minute dilutions for severe chronic joint pain and ringworm.',
    preparationMethod: 'Topical application in heavily diluted herbal oils only.',
    dosage: 'Apply drop of diluted oil topically once daily.',
    warnings: 'EXTREMELY DANGEROUS: Croton oil is a violent purgative and mucosal irritant. Lethal in small oral doses. Never ingest.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Croton tiglium).',
  },
  {
    localName: 'Tubang-Amerikano',
    scientificName: 'Jatropha multifida',
    cebuanoName: 'Mana',
    englishName: 'Coral Plant / Physic Nut cousin',
    category: 'Wound Care & Hemostatic',
    medicinalUses: 'Milky sap applied directly onto fresh cuts and scratches to stop bleeding and promote rapid wound closure.',
    preparationMethod: 'Dab a drop of clear stem sap directly onto clean minor cut.',
    dosage: 'Apply once topically.',
    warnings: 'Seeds are toxic: do not ingest. For topical hemostatic application only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Jatropha multifida).',
  },
  {
    localName: 'Ubi',
    scientificName: 'Dioscorea alata',
    cebuanoName: 'Ube',
    englishName: 'Purple Yam',
    category: 'Nutritional & General Wellness',
    medicinalUses: 'Tuber rich in anthocyanins and dietary fiber: soothing food for gastritis, hemorrhoids, and convalescent energy.',
    preparationMethod: 'Boil or steam washed tuber until soft.',
    dosage: 'Consume 100g as part of regular diet.',
    warnings: 'Must be cooked thoroughly before eating.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Dioscorea alata).',
  },
  {
    localName: 'Ubi-ubihan',
    scientificName: 'Dioscorea bulbifera',
    cebuanoName: 'Bayag-toro',
    englishName: 'Air Potato',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Roasted aerial bulbils applied as a warm poultice to boils, carbuncles, and swelling.',
    preparationMethod: 'Roast aerial tuber, peel, crush into paste, and apply to closed boils.',
    dosage: 'Apply poultice for 20 minutes twice daily.',
    warnings: 'Raw bulbils of wild varieties contain toxic dioscorine. Must be roasted or boiled before application.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Dioscorea bulbifera).',
  },
  {
    localName: 'Ugat-pula',
    scientificName: 'Morinda umbellata',
    cebuanoName: 'Noni-balagun',
    englishName: 'Climbing Noni',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Root decoction used for chronic dysentery, fevers, and as an anthelmintic.',
    preparationMethod: 'Boil 10g dried roots in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/3 cup twice daily.',
    warnings: 'Astringent root: use in moderation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Morinda umbellata).',
  },
  {
    localName: 'Utong',
    scientificName: 'Vigna unguiculata',
    cebuanoName: 'Sitaw',
    englishName: 'Cowpea / String Bean',
    category: 'Nutritional & General Wellness',
    medicinalUses: 'Pods and seeds provide easily digestible protein and soluble fiber to support glycemic control and heart health.',
    preparationMethod: 'Cook fresh pods in soups or vegetable dishes.',
    dosage: 'Eat regularly as part of balanced diet.',
    warnings: 'Safe, nutritious Philippine staple vegetable.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Vigna unguiculata).',
  },
  {
    localName: 'Waling-waling',
    scientificName: 'Vanda sanderiana',
    cebuanoName: 'Waling-waling',
    englishName: 'Queen of Philippine Orchids',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Traditional indigenous tonic wash made from pseudobulbs for cooling skin inflammation and soothing burns.',
    preparationMethod: 'Crush clean leaf tissue into cooling poultice.',
    dosage: 'Apply topically for 15 minutes.',
    warnings: 'Endangered and strictly protected national floral treasure: only cultivated nursery clippings should be studied.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Vanda sanderiana).',
  },
  {
    localName: 'Yantok',
    scientificName: 'Calamus rotang',
    cebuanoName: 'Uway-rotang',
    englishName: 'Rattan Cane',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Bitter root decoction traditionally taken for chronic dysentery, fevers, and biliousness.',
    preparationMethod: 'Boil 10g root in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily.',
    warnings: 'Safe in traditional moderate doses.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Calamus rotang).',
  },
  {
    localName: 'Yate',
    scientificName: 'Tectona grandis',
    cebuanoName: 'Tekla',
    englishName: 'Teak Tree',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Astringent leaves and bark used as a gargle for sore throat, stomatitis, and poultice for skin inflammation.',
    preparationMethod: 'Boil 10g dried leaves in 2 cups of water for 15 minutes.',
    dosage: 'Gargle 3 times daily; use as skin wash.',
    warnings: 'For topical gargle and wash.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Tectona grandis).',
  },
  {
    localName: 'Zapote-negro',
    scientificName: 'Diospyros nigra',
    cebuanoName: 'Black Sapote',
    englishName: 'Chocolate Pudding Fruit',
    category: 'Nutritional & General Wellness',
    medicinalUses: 'Fruit is exceptionally rich in vitamin C and antioxidants, supporting immune defense and digestive regularity.',
    preparationMethod: 'Consume ripe soft black pulp fresh.',
    dosage: '1 fruit serving daily.',
    warnings: 'Unripe fruit is astringent and caustic; eat only when completely soft and dark brown/black inside.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Diospyros nigra).',
  },
  {
    localName: 'Ablan',
    scientificName: 'Barleria prionitis',
    cebuanoName: 'Kuranta',
    englishName: 'Porcupine Flower',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Leaf juice applied for bleeding gums and toothache; leaf decoction used for fevers and bronchial catarrh.',
    preparationMethod: 'Squeeze juice from fresh leaves and apply with cotton to gums; or boil 10g leaves in 2 cups of water.',
    dosage: 'Apply to gums 2-3 times daily; drink 1/2 cup decoction twice daily for cough.',
    warnings: 'Safe oral rinse. Avoid swallowing excessive amounts.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Barleria prionitis).',
  },
  {
    localName: 'Alim',
    scientificName: 'Melanolepis multiglandulosa',
    cebuanoName: 'Alum',
    englishName: 'Alim Tree',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Fresh leaves wilted over low heat applied as a soothing poultice for pleurisy, swelling, and skin eczema.',
    preparationMethod: 'Warm fresh leaves with a little coconut oil and bind over affected skin.',
    dosage: 'Apply once daily for 30 minutes.',
    warnings: 'External application recommended.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Melanolepis multiglandulosa).',
  },
  {
    localName: 'Amlong',
    scientificName: 'Epipremnum pinnatum',
    cebuanoName: 'Tibatib',
    englishName: 'Centipede Tongavine',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Warm leaf poultice applied to relieve joint stiffness, sprains, and chest congestion.',
    preparationMethod: 'Pound fresh leaves, warm gently over flame, and wrap around aching joint.',
    dosage: 'Apply warm poultice for 30 minutes daily.',
    warnings: 'Contains calcium oxalate crystals: do not ingest raw leaves.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Epipremnum pinnatum).',
  },
  {
    localName: 'Anilao',
    scientificName: 'Colona serratifolia',
    cebuanoName: 'Anilaw',
    englishName: 'Serrated Colona',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Bark and leaves boiled as an astringent gargle for mouth ulcers and as a wash for chronic wounds.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes. Cool and strain.',
    dosage: 'Gargle 3 times daily; rinse skin sores twice daily.',
    warnings: 'Safe astringent wash.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Colona serratifolia).',
  },
  {
    localName: 'Antipolo',
    scientificName: 'Artocarpus blancoi',
    cebuanoName: 'Tipolo',
    englishName: 'Blanco\'s Breadfruit',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Milky sap applied to ringworm, skin boils, and minor burns; bark decoction used for diarrhea.',
    preparationMethod: 'Dab fresh milky sap directly over cleansed skin lesions.',
    dosage: 'Apply topically once daily.',
    warnings: 'For external use. Avoid contact with eyes.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Artocarpus blancoi).',
  },
  {
    localName: 'Api-api',
    scientificName: 'Avicennia officinalis',
    cebuanoName: 'Api-api-dako',
    englishName: 'Indian Mangrove',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Bark decoction used as an astringent wash for scabies, ulcers, and hemorrhoids.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Apply as external wash twice daily.',
    warnings: 'External use only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Avicennia officinalis).',
  },
  {
    localName: 'Apulid',
    scientificName: 'Eleocharis dulcis',
    cebuanoName: 'Katsubong-tubig',
    englishName: 'Chinese Water Chestnut',
    category: 'Nutritional & General Wellness',
    medicinalUses: 'Corms possess antibiotic puchiin; eaten as a cooling food to soothe gastritis, fevers, and urinary discomfort.',
    preparationMethod: 'Peel and consume crisp corms fresh or boiled in soups.',
    dosage: 'Eat 50-100g fresh corms as dietary supplement.',
    warnings: 'Peel thoroughly and wash clean before consuming.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Eleocharis dulcis).',
  },
  {
    localName: 'Arikway',
    scientificName: 'Curculigo orchioides',
    cebuanoName: 'Sinta-sinta',
    englishName: 'Golden Eye-grass',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Rhizome decoction taken as a restorative tonic for fatigue, chronic arthritis, and urinary gravel.',
    preparationMethod: 'Boil 10g cleaned rhizomes in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Mildly warming tonic: avoid in high acute fevers.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Curculigo orchioides).',
  },
  {
    localName: 'Babako',
    scientificName: 'Bidens pilosa',
    cebuanoName: 'Tubak-tubak',
    englishName: 'Spanish Needles / Beggar-ticks',
    category: 'Digestive & Anti-inflammatory',
    medicinalUses: 'Whole plant tea used for gastroenteritis, stomach ulcers, diabetes support, and sore throat gargle.',
    preparationMethod: 'Boil 15g fresh flowering herb in 2 cups of water for 10 minutes.',
    dosage: 'Drink 1/2 cup twice daily after meals.',
    warnings: 'Safe traditional tea. Monitor blood sugar if taking prescription hypoglycemic drugs.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Bidens pilosa).',
  },
  {
    localName: 'Bagauak',
    scientificName: 'Clerodendrum quadriloculare',
    cebuanoName: 'Bagawak-morado',
    englishName: 'Bronze Glorybower / Starburst Bush',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Leaves applied as a warm poultice to soothe rheumatic joint swellings, bruises, and sprains.',
    preparationMethod: 'Crush clean leaves, warm slightly with coconut oil, and wrap around swollen joint.',
    dosage: 'Apply once daily for 30 minutes.',
    warnings: 'For external use only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Clerodendrum quadriloculare).',
  },
  {
    localName: 'Bagnag',
    scientificName: 'Clerodendrum minahassae',
    cebuanoName: 'Kasopangil-gubat',
    englishName: 'Minahassa Glorybower',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Root decoction used for gastrointestinal cramps, fevers, and as an anthelmintic.',
    preparationMethod: 'Boil 10g dried roots in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily.',
    warnings: 'Avoid in pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Clerodendrum minahassae).',
  },
  {
    localName: 'Balasbas',
    scientificName: 'Pluchea indica',
    cebuanoName: 'Lagundi-lati',
    englishName: 'Indian Camphorweed / Marsh Fleabane',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Aromatic leaf decoction taken for dysentery, stomach cramps, bad breath, and fevers.',
    preparationMethod: 'Boil 10g leaves in 2 cups of water for 10 minutes.',
    dosage: 'Drink 1/2 cup twice daily; gargle for halitosis.',
    warnings: 'Safe aromatic tea.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pluchea indica).',
  },
  {
    localName: 'Balatbat',
    scientificName: 'Licuala spinosa',
    cebuanoName: 'Pilig',
    englishName: 'Mangrove Fan Palm',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Bark and roots decocted for chronic dysentery, intestinal bleeding, and diarrhea.',
    preparationMethod: 'Boil 10g dried roots in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily.',
    warnings: 'Astringent: use during acute looseness only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Licuala spinosa).',
  },
  {
    localName: 'Balingway',
    scientificName: 'Flagellaria indica',
    cebuanoName: 'Huag',
    englishName: 'Whip Vine / False Rattan',
    category: 'Renal & Diuretic',
    medicinalUses: 'Stem and leaf decoctions used as a cooling diuretic, and root infusion to relieve sore throat and toothache.',
    preparationMethod: 'Boil 15g leaves and tender stems in 3 cups of water for 15 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Safe diuretic; ensure adequate fluid intake.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Flagellaria indica).',
  },
  {
    localName: 'Balitadhan',
    scientificName: 'Cissus repens',
    cebuanoName: 'Alupidan',
    englishName: 'Creeping Vine / Cissus',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Fresh leaves pounded into a paste to soothe boils, muscular aches, and sprains.',
    preparationMethod: 'Crush fresh leaves and apply directly over bruised muscle or closed boil.',
    dosage: 'Apply topically for 20 minutes twice daily.',
    warnings: 'External use only. Avoid contact with broken skin.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Cissus repens).',
  },
  {
    localName: 'Bangkoro',
    scientificName: 'Morinda bracteata',
    cebuanoName: 'Apalot',
    englishName: 'Bracteate Noni',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Leaves and fruit extract applied to relieve skin inflammation, ulcers, and joint stiffness.',
    preparationMethod: 'Warm fresh leaves over fire and bandage over stiff joints; apply juice to minor ulcers.',
    dosage: 'Apply once daily for 30 minutes.',
    warnings: 'Pungent odor; safe external and dietary tonic.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Morinda bracteata).',
  },
  {
    localName: 'Bani',
    scientificName: 'Pongamia pinnata',
    cebuanoName: 'Baluk-baluk',
    englishName: 'Indian Beech / Pongam Tree',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Seed oil (karanja oil) applied topically for chronic eczema, scabies, leprosy sores, and rheumatic swelling.',
    preparationMethod: 'Mix seed oil with coconut oil (1:4 ratio) and apply to affected skin.',
    dosage: 'Apply topically once daily at night.',
    warnings: 'TOXIC INTERNALLY: Karanja oil must never be ingested. External application only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pongamia pinnata).',
  },
  {
    localName: 'Basikong',
    scientificName: 'Ficus botryocarpa',
    cebuanoName: 'Tebeg-gamay',
    englishName: 'Cluster Fig cousin',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Bark decoction used for digestive catarrh, stomach ache, and as an astringent wash.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily.',
    warnings: 'Safe in traditional moderation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ficus botryocarpa).',
  },
  {
    localName: 'Batuan',
    scientificName: 'Garcinia morella',
    cebuanoName: 'Batuan-pula',
    englishName: 'Gamboge Tree',
    category: 'Digestive & Parasitic (Caution)',
    medicinalUses: 'Resin historically used as a drastic hydragogue cathartic and for intestinal worms.',
    preparationMethod: 'Historical remedy: modern medical advice restricts raw internal use due to gastrointestinal irritation.',
    dosage: 'External antiseptic wash only.',
    warnings: 'POTENT PURGATIVE: Can cause severe vomiting and dehydration if taken internally. Do not self-administer.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Garcinia morella).',
  },
  {
    localName: 'Bayag-kambing',
    scientificName: 'Caesalpinia bonduc',
    cebuanoName: 'Kalambibit',
    englishName: 'Grey Nickernut / Fever Nut',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Extremely bitter seeds roasted and ground into powder for malaria, intermittent fevers, and colic.',
    preparationMethod: 'Crush 1 roasted seed kernel and take with warm water or honey.',
    dosage: 'Take once daily during acute febrile episodes.',
    warnings: 'Bitter: high doses cause vomiting. Avoid in pregnancy.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Caesalpinia bonduc).',
  },
  {
    localName: 'Bikal',
    scientificName: 'Schizostachyum diffusum',
    cebuanoName: 'Usio',
    englishName: 'Climbing Bamboo',
    category: 'Ophthalmic & Dermatological',
    medicinalUses: 'Water trapped in internodes used as a cooling sterile wash for inflamed eyes and sunburn.',
    preparationMethod: 'Collect fresh clear liquid from unpierced stem internode using sterile syringe/dropper.',
    dosage: 'Rinse eye or dab onto sunburnt skin.',
    warnings: 'Ensure bamboo is freshly cut and uncontaminated.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Schizostachyum diffusum).',
  },
  {
    localName: 'Binunga-gubat',
    scientificName: 'Macaranga grandifolia',
    cebuanoName: 'Takip-asin',
    englishName: 'Coral Tree cousin / Giant-leaved Macaranga',
    category: 'Oral & Antiseptic Care',
    medicinalUses: 'Resin and bark decoction used as an astringent gargle for aphthous mouth ulcers and washing wounds.',
    preparationMethod: 'Boil 10g bark in 2 cups of water for 15 minutes.',
    dosage: 'Gargle 3 times daily; rinse skin sores twice daily.',
    warnings: 'Safe topical antiseptic wash.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Macaranga grandifolia).',
  },
  {
    localName: 'Bitaog-gubat',
    scientificName: 'Calophyllum soulattri',
    cebuanoName: 'Palo Maria del Monte',
    englishName: 'Bitanghol',
    category: 'Pain Relief & Anti-inflammatory',
    medicinalUses: 'Bark decoction and resin applied to relieve rheumatic pains, backaches, and chronic skin ulcers.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes; apply topically as wash or compress.',
    dosage: 'Apply warm compress once daily for 20 minutes.',
    warnings: 'For external use.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Calophyllum soulattri).',
  },
  {
    localName: 'Bungalon',
    scientificName: 'Avicennia alba',
    cebuanoName: 'Miapit',
    englishName: 'White Mangrove',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Bark and resin used to wash chronic skin sores, scabies, and ulcerations.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Wash affected skin twice daily.',
    warnings: 'External wash only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Avicennia alba).',
  },
  {
    localName: 'Buyo-gubat',
    scientificName: 'Piper celtidiforme',
    cebuanoName: 'Lid-lid',
    englishName: 'Celtis-leaved Pepper',
    category: 'Respiratory',
    medicinalUses: 'Aromatic leaves boiled for relief of chest congestion, colds, and applied warm over swollen joints.',
    preparationMethod: 'Boil 5-7 fresh leaves in 2 cups of water for 10 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Safe aromatic tea.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Piper celtidiforme).',
  },
  {
    localName: 'Dangkalan',
    scientificName: 'Calophyllum blancoi',
    cebuanoName: 'Bitanghol-pula',
    englishName: 'Blanco\'s Calophyllum',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Oleoresin applied as a soothing dressing for chronic wounds, burns, and joint aches.',
    preparationMethod: 'Apply a thin layer of resin-infused oil onto clean gauze over sores.',
    dosage: 'Apply once daily.',
    warnings: 'For external use only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Calophyllum blancoi).',
  },
  {
    localName: 'Dao-dao',
    scientificName: 'Pometia pinnata',
    cebuanoName: 'Malugay',
    englishName: 'Fijian Longan / Kasai',
    category: 'Fevers & Gastrointestinal',
    medicinalUses: 'Bark decoction used for fevers, diarrhea, and as a mouthwash for toothache.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/3 cup twice daily for diarrhea; use as oral rinse.',
    warnings: 'Astringent: avoid in constipation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Pometia pinnata).',
  },
  {
    localName: 'Dita-lati',
    scientificName: 'Cerbera manghas',
    cebuanoName: 'Barakbak',
    englishName: 'Sea Mango',
    category: 'Dermatological (Strict Caution)',
    medicinalUses: 'Bark and latex used historically in minute topical amounts for chronic ringworm and scabies.',
    preparationMethod: 'External topical wash in heavy dilution only.',
    dosage: 'Apply to lesion once daily.',
    warnings: 'LETHAL CARDIOTOXIN (Cerberin): Seeds and sap contain fatal cardiac glycosides. Never ingest. Strictly external caution.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Cerbera manghas).',
  },
  {
    localName: 'Galamay-amo',
    scientificName: 'Schefflera odorata',
    cebuanoName: 'Lima-lima',
    englishName: 'Fragrant Schefflera',
    category: 'Respiratory',
    medicinalUses: 'Leaf decoction and steam inhalation widely used in Philippine folk medicine for cough, asthma, bronchitis, and arthritis.',
    preparationMethod: 'Boil 10 fresh leaves in 3 cups of water for 15 minutes. Strain.',
    dosage: 'Drink 1/2 cup 3 times daily for cough and bronchial relief.',
    warnings: 'Safe herbal cough remedy. Prepare fresh daily.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Schefflera odorata).',
  },
  {
    localName: 'Gatas-gatas-pula',
    scientificName: 'Euphorbia prostrata',
    cebuanoName: 'Tawa-tawa-gamay',
    englishName: 'Prostrate Spurge',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Whole plant decoction taken for diarrhea, bleeding hemorrhoids, and dysentery.',
    preparationMethod: 'Boil 10g dried whole plant in 2 cups of water for 10 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Contains mild latex. Discontinue if stomach cramps occur.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Euphorbia prostrata).',
  },
  {
    localName: 'Gatasan',
    scientificName: 'Garcinia venulosa',
    cebuanoName: 'Gatasan-pula',
    englishName: 'Veined Garcinia',
    category: 'Digestive & Gastrointestinal',
    medicinalUses: 'Bark and fruit decoction used for acute diarrhea, dysentery, and as an astringent wash.',
    preparationMethod: 'Boil 10g dried bark in 2 cups of water for 15 minutes.',
    dosage: 'Drink 1/4 cup twice daily.',
    warnings: 'Astringent: use during acute diarrhea only.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Garcinia venulosa).',
  },
  {
    localName: 'Giting-giting',
    scientificName: 'Ipomoea pes-caprae',
    cebuanoName: 'Bamban-lati',
    englishName: 'Beach Morning Glory / Railroad Vine',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Boiled leaves applied directly as a poultice to soothe painful jellyfish stings, boil inflammation, and joint pain.',
    preparationMethod: 'Crush fresh leaves and steep in hot water; apply warm leaf mass directly over jellyfish sting.',
    dosage: 'Apply topically for 20-30 minutes as immediate soothing poultice.',
    warnings: 'External poultice. Remove stingers with seawater before applying.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Ipomoea pes-caprae).',
  },
  {
    localName: 'Gogo-gubat',
    scientificName: 'Entada rheedii',
    cebuanoName: 'Bayogo',
    englishName: 'African Dream Herb / Giant St. Thomas Bean',
    category: 'Dermatological & Scalp',
    medicinalUses: 'Bark and seed pulp soaked in water to produce rich natural saponin lather for cleansing hair, scalp, and dandruff.',
    preparationMethod: 'Pound dried bark or seed kernel into fibrous shreds, soak in water, and rub to form lather.',
    dosage: 'Use as natural hair shampoo 2 times weekly.',
    warnings: 'Do not get saponin lather into eyes; causes burning sensation.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Entada rheedii).',
  },
  {
    localName: 'Gulasiman-gubat',
    scientificName: 'Trianthema portulacastrum',
    cebuanoName: 'Toston',
    englishName: 'Desert Horse Purslane',
    category: 'Renal & Diuretic',
    medicinalUses: 'Whole plant decoction used as a diuretic for dropsy, edema, liver swelling, and fevers.',
    preparationMethod: 'Boil 15g fresh plant in 2 cups of water for 10 minutes.',
    dosage: 'Drink 1/2 cup twice daily.',
    warnings: 'Excessive consumption causes vomiting due to saponin content. Follow dosage.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Trianthema portulacastrum).',
  },
  {
    localName: 'Gumamela-de-China',
    scientificName: 'Hibiscus mutabilis',
    cebuanoName: 'Mapula-puti',
    englishName: 'Confederate Rose / Dixie Rosemallow',
    category: 'Dermatological & Skin Care',
    medicinalUses: 'Flowers and leaves applied as a cooling emollient poultice on skin boils, burns, and swellings.',
    preparationMethod: 'Pound fresh flowers into paste and apply over skin inflammation.',
    dosage: 'Apply for 20 minutes twice daily.',
    warnings: 'Safe topical emollient.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Hibiscus mutabilis).',
  },
  {
    localName: 'Hagonoy-gubat',
    scientificName: 'Wedelia biflora',
    cebuanoName: 'Hagonoy-dagat',
    englishName: 'Beach Sunflower / Sea Daisy',
    category: 'Wound Care & Hemostatic',
    medicinalUses: 'Leaves pounded and applied as a hemostatic dressing to stop bleeding from cuts and soothe insect bites.',
    preparationMethod: 'Crush fresh leaves between fingers and press directly onto minor cuts.',
    dosage: 'Apply once as immediate field hemostatic.',
    warnings: 'Clean wound thoroughly with clean water before application.',
    informationSource: 'StuartXchange Philippine Medicinal Plants (Wedelia biflora).',
  },
];

async function verifyZeroDuplicates() {
  const dbHerbs = await prisma.herb.findMany({
    select: {
      id: true,
      localName: true,
      scientificName: true,
    },
  });

  const dbSciMap = new Map(dbHerbs.map((h) => [h.scientificName.toLowerCase().trim(), h.localName]));
  const dbLocalMap = new Map(dbHerbs.map((h) => [h.localName.toLowerCase().trim(), h.scientificName]));

  console.log(`Checking ${proposedHerbs.length} proposed herbs against ${dbHerbs.length} database records...`);

  const duplicates: string[] = [];
  const proposedSciSet = new Set<string>();
  const proposedLocalSet = new Set<string>();

  for (const h of proposedHerbs) {
    const sciLower = h.scientificName.toLowerCase().trim();
    const localLower = h.localName.toLowerCase().trim();

    if (dbSciMap.has(sciLower)) {
      duplicates.push(`SCIENTIFIC NAME DUPLICATE with DB: "${h.scientificName}" (DB local name: "${dbSciMap.get(sciLower)}")`);
    }
    if (dbLocalMap.has(localLower)) {
      duplicates.push(`LOCAL NAME DUPLICATE with DB: "${h.localName}" (DB sci name: "${dbLocalMap.get(localLower)}")`);
    }

    if (proposedSciSet.has(sciLower)) {
      duplicates.push(`INTERNAL DUPLICATE (scientific): "${h.scientificName}"`);
    }
    proposedSciSet.add(sciLower);

    if (proposedLocalSet.has(localLower)) {
      duplicates.push(`INTERNAL DUPLICATE (local): "${h.localName}"`);
    }
    proposedLocalSet.add(localLower);
  }

  if (duplicates.length > 0) {
    console.error(`Found ${duplicates.length} duplicate issues:`);
    duplicates.forEach((d) => console.error('  - ' + d));
    process.exit(1);
  } else {
    console.log(`SUCCESS: ZERO DUPLICATES! All ${proposedHerbs.length} herbs are 100% unique against DB and within the list!`);
  }
}

verifyZeroDuplicates()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
